on:
  - push

permissions:
  contents: read
  id-token: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: script
        timeout-minutes: 10
        with:
          debug: true
          script: |
            const webIdentityToken = await core.getIDToken('https://oidc-api-token.rubygems.org');
            const res = await fetch(
              'https://oidc-api-token.rubygems.org/api/v1/oidc/api_key_roles/1/assume_role',
              {
                method: "post",
                body: JSON.stringify({"jwt": webIdentityToken}),
                headers: {
                  'content-type': 'application/json',
                  'accept': 'application/json'
                }
              }
            )
            const obj = await res.json();
            const rubygemsApiKey = obj['rubygems_api_key'];
            core.exportVariable('RUBYGEMS_API_KEY', rubygemsApiKey);
            core.setSecret(rubygemsApiKey);
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.1"
          bundler-cache: true
      - name: Release
        run: bundle exec rake release
