on:
  - push

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        roleToken:
          - "rg_oidc_akr_4w2msawg1kstcox9nqga"
        gem-server:
          - "https://rubygems.org"
        include:
          - roleToken: rg_oidc_akr_4w2msawg1kstcox9nqga
            gem-server: "https://oidc-api-token.rubygems.org"
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: rubygems/configure-rubygems-credentials@main
        with:
          role-to-assume: ${{ matrix.roleToken }}
          gem-server: ${{ matrix.gem-server }}
          audience: ${{ matrix.gem-server }}
      - uses: actions/checkout@v3
      - name: Set remote URL
        run: |
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.1"
          bundler-cache: true
      - name: Release
        run: bundle exec rake release
        env:
          TAG_PREFIX: "${{ matrix.roleToken }}-"
          GEM_HOST: "${{ matrix.gem-server }}"
